add_executable(sanity_test sanity_test.cpp)
add_test(NAME SanityTest COMMAND sanity_test)

add_executable(VmIdTest VmIdTest.cpp)
target_link_libraries(VmIdTest PRIVATE VmDomain)
add_test(NAME VmIdTest COMMAND VmIdTest)

add_executable(VmConfigTest VmConfigTest.cpp)
target_link_libraries(VmConfigTest PRIVATE VmDomain)
add_test(NAME VmConfigTest COMMAND VmConfigTest)

add_executable(StorageAttachmentTest StorageAttachmentTest.cpp)
target_link_libraries(StorageAttachmentTest PRIVATE VmDomain)
add_test(NAME StorageAttachmentTest COMMAND StorageAttachmentTest)

add_executable(VmManagerTest VmManagerTest.cpp)
target_link_libraries(VmManagerTest PRIVATE VmManagement InMemoryInfrastructure)
add_test(NAME VmManagerTest COMMAND VmManagerTest)

add_executable(CompositionTest CompositionTest.cpp)
target_link_libraries(CompositionTest PRIVATE ApplicationBootstrap VmManagement)
add_test(NAME CompositionTest COMMAND CompositionTest)

add_executable(QemuCommandBuilderTest QemuCommandBuilderTest.cpp)
target_link_libraries(QemuCommandBuilderTest PRIVATE QemuInfrastructure)
add_test(NAME QemuCommandBuilderTest COMMAND QemuCommandBuilderTest)

add_executable(QemuLocatorTest QemuLocatorTest.cpp)
target_link_libraries(QemuLocatorTest PRIVATE QemuInfrastructure)
add_test(NAME QemuLocatorTest COMMAND QemuLocatorTest)

add_executable(QemuImgLocatorTest QemuImgLocatorTest.cpp)
target_link_libraries(QemuImgLocatorTest PRIVATE QemuInfrastructure)
add_test(NAME QemuImgLocatorTest COMMAND QemuImgLocatorTest)

add_executable(QemuProcessTest QemuProcessTest.cpp)
target_link_libraries(QemuProcessTest PRIVATE QemuInfrastructure)
add_test(NAME QemuProcessTest COMMAND QemuProcessTest)

add_executable(QemuQuotingTest QemuQuotingTest.cpp)
target_link_libraries(QemuQuotingTest PRIVATE QemuInfrastructure)
add_test(NAME QemuQuotingTest COMMAND QemuQuotingTest)

add_executable(QmpClientTest QmpClientTest.cpp)
target_link_libraries(QmpClientTest PRIVATE QemuInfrastructure)
add_test(NAME QmpClientTest COMMAND QmpClientTest)
